Notification for resolved errors
umts/bojangles pull request #30
Opened 2017-02-02 19:45 UTC by mboneil10

Closes #25

2017-02-08 15:54 UTC, dfaulken requested changes
Small changes.

2017-02-08 15:54 UTC, dfaulken commented on lib/bojangles.rb
> +  def message_list(error_messages, current)
Boolean arguments are generally an antipattern, that is, it's difficult to tell from looking at them what they're for.

I'd use a kwarg here.

2017-02-08 15:54 UTC, dfaulken commented on lib/bojangles.rb
> +    if current == true
For checking the value of a boolean, anyhow, you don't need `== true`.

2017-02-08 15:54 UTC, dfaulken commented on lib/bojangles.rb
> +  def message_list(error_messages, current)
For example

```ruby
message_list(resolved_error_messages, current: true)
```

And

```ruby
def message_list(error_messages, current:)
```

which will require the kwarg.

2017-02-08 19:25 UTC, Anbranin commented on lib/bojangles.rb
> +  def message_list(error_messages, current)
wow I did not know what a "quarg" was for a while. I'm like what sorcery is in Ruby > 2 that I didn't know about

2017-02-08 19:33 UTC, werebus commented on lib/bojangles.rb
> +  def message_list(error_messages, current)
![quarg-cheese](https://cloud.githubusercontent.com/assets/240275/22753860/991b56ae-ee0b-11e6-9601-82b4823723fd.jpg)

2017-02-08 23:48 UTC, dfaulken commented on lib/bojangles.rb
> +  def message_list(error_messages, current)
Yep that's it

2017-02-13 15:35 UTC, mboneil10 commented on lib/bojangles.rb
> +    if current == true
Don't know what I was thinking.

2017-02-15 00:38 UTC, Anbranin approved these changes

2017-02-15 15:02 UTC, dfaulken approved these changes

2017-02-15 15:02 UTC, merged